#!/bin/bash
# cp ~notes/html-* ./src/notes
mkdir -p dist
find ./src/notes -type f -iname "html-*.md" | while IFS= read -r F; do
	name=$(echo "$F" | sed -r "s/html-//;s/.+\/(.+)\..+/\1/;s/ /_/g")
	out="./dist/$name.html"
	head=$(sed "s/:title:/$name/" < ./src/html/header.html)
	foot=$(sed 's|"|\"|g' < ./src/html/footer.html)
	dom=$(cat "$F")
	echo "${head}${dom//<div class=\"mod-footer mod-ui\"><\/div><\/div><\/div><\/div>/${foot}}" > "$out"
done
